import type { OTCAsset } from "./price-engine/types"

export const OTC_ASSETS: OTCAsset[] = [
  // Crypto
  {
    id: "1",
    symbol: "BTC/USD",
    name: "Bitcoin",
    category: "crypto",
    basePrice: 67500.0,
    volatility: 0.0012,
    payout: 96,
    isActive: true,
  },
  {
    id: "2",
    symbol: "LTC/USD",
    name: "Litecoin",
    category: "crypto",
    basePrice: 85.50,
    volatility: 0.0014,
    payout: 96,
    isActive: true,
  },
  {
    id: "3",
    symbol: "ADA/USD",
    name: "Cardano",
    category: "crypto",
    basePrice: 0.45,
    volatility: 0.0015,
    payout: 96,
    isActive: true,
  },
  {
    id: "4",
    symbol: "BNB/USD",
    name: "BNB",
    category: "crypto",
    basePrice: 580.0,
    volatility: 0.001,
    payout: 96,
    isActive: true,
  },
  {
    id: "5",
    symbol: "ETH/USD",
    name: "Ethereum",
    category: "crypto",
    basePrice: 3450.0,
    volatility: 0.0014,
    payout: 96,
    isActive: true,
  },
  {
    id: "6",
    symbol: "SOL/USD",
    name: "Solana",
    category: "crypto",
    basePrice: 145.0,
    volatility: 0.0016,
    payout: 96,
    isActive: true,
  },
  // Crypto OTC
  {
    id: "7",
    symbol: "BTC/USD-OTC",
    name: "Bitcoin OTC",
    category: "crypto",
    basePrice: 67500.0,
    volatility: 0.0012,
    payout: 96,
    isActive: true,
  },
  {
    id: "8",
    symbol: "LTC/USD-OTC",
    name: "Litecoin OTC",
    category: "crypto",
    basePrice: 85.50,
    volatility: 0.0014,
    payout: 96,
    isActive: true,
  },
  {
    id: "9",
    symbol: "ADA/USD-OTC",
    name: "Cardano OTC",
    category: "crypto",
    basePrice: 0.45,
    volatility: 0.0015,
    payout: 96,
    isActive: true,
  },
  // Forex OTC
  {
    id: "10",
    symbol: "EUR/USD-OTC",
    name: "EUR/USD OTC",
    category: "forex",
    basePrice: 1.0856,
    volatility: 0.0005,
    payout: 96,
    isActive: true,
  },
  {
    id: "11",
    symbol: "JPY/USD",
    name: "JPY/USD",
    category: "forex",
    basePrice: 0.0067,
    volatility: 0.0006,
    payout: 96,
    isActive: true,
  },
  {
    id: "12",
    symbol: "JPY/USD-OTC",
    name: "JPY/USD OTC",
    category: "forex",
    basePrice: 0.0067,
    volatility: 0.0006,
    payout: 96,
    isActive: true,
  },
  // Stocks
  {
    id: "13",
    symbol: "NFLX",
    name: "Netflix USD",
    category: "stocks",
    basePrice: 625.0,
    volatility: 0.001,
    payout: 96,
    isActive: true,
  },
  {
    id: "14",
    symbol: "TSLA",
    name: "Tesla USD",
    category: "stocks",
    basePrice: 175.0,
    volatility: 0.0015,
    payout: 96,
    isActive: true,
  },
  {
    id: "15",
    symbol: "MSFT",
    name: "Microsoft USD",
    category: "stocks",
    basePrice: 420.0,
    volatility: 0.0008,
    payout: 96,
    isActive: true,
  },
  {
    id: "16",
    symbol: "PYPL",
    name: "PayPal",
    category: "stocks",
    basePrice: 65.0,
    volatility: 0.0012,
    payout: 96,
    isActive: true,
  },
  {
    id: "17",
    symbol: "AMZN",
    name: "Amazon",
    category: "stocks",
    basePrice: 178.0,
    volatility: 0.001,
    payout: 96,
    isActive: true,
  },
  {
    id: "18",
    symbol: "MA",
    name: "Mastercard",
    category: "stocks",
    basePrice: 465.0,
    volatility: 0.0008,
    payout: 96,
    isActive: true,
  },
  // Stocks OTC
  {
    id: "19",
    symbol: "AAPL-OTC",
    name: "Apple OTC",
    category: "stocks",
    basePrice: 172.0,
    volatility: 0.0008,
    payout: 96,
    isActive: true,
  },
  {
    id: "20",
    symbol: "DIS-OTC",
    name: "Disney OTC",
    category: "stocks",
    basePrice: 112.0,
    volatility: 0.001,
    payout: 96,
    isActive: true,
  },
  {
    id: "21",
    symbol: "MA-OTC",
    name: "Mastercard OTC",
    category: "stocks",
    basePrice: 465.0,
    volatility: 0.0008,
    payout: 96,
    isActive: true,
  },
  {
    id: "22",
    symbol: "DOGE/USD-OTC",
    name: "Doge OTC",
    category: "crypto",
    basePrice: 0.12,
    volatility: 0.002,
    payout: 96,
    isActive: true,
  },
  {
    id: "23",
    symbol: "UVS",
    name: "Univision",
    category: "stocks",
    basePrice: 4.50,
    volatility: 0.0015,
    payout: 96,
    isActive: true,
  },
]

export function getAssetBySymbol(symbol: string): OTCAsset | undefined {
  return OTC_ASSETS.find((a) => a.symbol === symbol)
}

export function getAssetsByCategory(category: string): OTCAsset[] {
  return OTC_ASSETS.filter((a) => a.category === category && a.isActive)
}
